/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    icons: Icon;
    illustrations: Illustration;
    avatars: Avatar;
    logos: Logo;
    services: Service;
    values: Value;
    statistics: Statistic;
    partners: Partner;
    testimonials: Testimonial;
    questions: Question;
    socials: Social;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  globals: {};
}
export interface User {
  id: string;
  first_name: string;
  last_name: string;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password: string | null;
}
export interface Icon {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
export interface Illustration {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
export interface Avatar {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
export interface Logo {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
export interface Service {
  id: string;
  title: string;
  order: number;
  description: string;
  illustration?: string | Illustration | null;
  published: boolean;
  updatedAt: string;
  createdAt: string;
}
export interface Value {
  id: string;
  title: string;
  description: string;
  icon?: string | Icon | null;
  order: number;
  published: boolean;
  updatedAt: string;
  createdAt: string;
}
export interface Statistic {
  id: string;
  value: string;
  order: number;
  description: string;
  icon?: string | Icon | null;
  published: boolean;
  updatedAt: string;
  createdAt: string;
}
export interface Partner {
  id: string;
  name: string;
  description?: string | null;
  logo?: string | Logo | null;
  order: number;
  published: boolean;
  updatedAt: string;
  createdAt: string;
}
export interface Testimonial {
  id: string;
  avatar?: string | Avatar | null;
  username: string;
  rating: number;
  date?: string | null;
  comment: string;
  order: number;
  published: boolean;
  updatedAt: string;
  createdAt: string;
}
export interface Question {
  id: string;
  question: string;
  answer: string;
  order: number;
  published: boolean;
  updatedAt: string;
  createdAt: string;
}
export interface Social {
  id: string;
  name: string;
  order: number;
  link: string;
  icon?: string | Icon | null;
  published: boolean;
  updatedAt: string;
  createdAt: string;
}
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
