/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    services: Service;
    'team-values': TeamValue;
    statistics: Statistic;
    faqs: Faq;
    testimonials: Testimonial;
    members: Member;
    orientations: Orientation;
    partners: Partner;
    jobs: Job;
    socials: Social;
    avatars: Avatar;
    documents: Document;
    icons: Icon;
    videos: Video;
    logos: Logo;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  globals: {};
}
export interface User {
  id: string;
  email: string;
  sub?: string | null;
  firstname?: string | null;
  lastname?: string | null;
  pictureURL?: string | null;
  role: 'root' | 'admin' | 'editor' | 'pending';
  updatedAt: string;
  createdAt: string;
}
export interface Service {
  id: string;
  title: string;
  description: string;
  order: number;
  published: boolean;
  updatedAt: string;
  createdAt: string;
}
export interface TeamValue {
  id: string;
  title: string;
  description: string;
  icon?: string | Icon | null;
  order: number;
  published: boolean;
  updatedAt: string;
  createdAt: string;
}
export interface Icon {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
export interface Statistic {
  id: string;
  title: string;
  description: string;
  order: number;
  published: boolean;
  updatedAt: string;
  createdAt: string;
}
export interface Faq {
  id: string;
  question: string;
  answer: string;
  order: number;
  published: boolean;
  updatedAt: string;
  createdAt: string;
}
export interface Testimonial {
  id: string;
  username: string;
  date: string;
  comment: string;
  avatar?: string | Avatar | null;
  order: number;
  published: boolean;
  updatedAt: string;
  createdAt: string;
}
export interface Avatar {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
export interface Member {
  id: string;
  firstname: string;
  lastname: string;
  department: 'direction-generale' | 'departement-interieur' | 'departement-exterieur' | 'departement-pedagogique';
  role: string;
  joinedAt: string;
  rank: '0' | '1' | '2' | '3';
  avatar?: string | Avatar | null;
  order: number;
  published: boolean;
  fullname?: string | null;
  updatedAt: string;
  createdAt: string;
}
export interface Orientation {
  id: string;
  name: string;
  description?: string | null;
  links?:
    | {
        label: string;
        link: string;
        order: number;
        id?: string | null;
      }[]
    | null;
  logo?: string | Logo | null;
  order: number;
  published: boolean;
  updatedAt: string;
  createdAt: string;
}
export interface Logo {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
export interface Partner {
  id: string;
  name: string;
  description?: string | null;
  links?:
    | {
        label: string;
        link: string;
        order: number;
        id?: string | null;
      }[]
    | null;
  logo?: string | Logo | null;
  order: number;
  published: boolean;
  updatedAt: string;
  createdAt: string;
}
export interface Job {
  id: string;
  role: string;
  status: 'active' | 'inactive';
  description: string;
  icon?: string | Icon | null;
  order: number;
  published: boolean;
  updatedAt: string;
  createdAt: string;
}
export interface Social {
  id: string;
  name: string;
  link: string;
  icon: string | Icon;
  order: number;
  published: boolean;
  updatedAt: string;
  createdAt: string;
}
export interface Document {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
export interface Video {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
